export enum Action {
  ToggleLight = 'ToggleLight',
  ToggleUpLight = 'ToggleUpLight',
  ToggleDownLight = 'ToggleDownLight',
  TurnOff = 'TurnOff',
  TurnOn = 'TurnOn',
  StartDimmer = 'StartDimmer',
  StartUpLightDimmer = 'StartUpLightDimmer',
  StartDownLightDimmer = 'StartDownLightDimmer',
  StartIncreasingBrightness = 'StartIncreasingBrightness',
  StartDecreasingBrightness = 'StartDecreasingBrightness',
  Stop = 'Stop',
  SetBrightness = 'SetBrightness',
  SetSpeed = 'SetSpeed',
  IncreaseSpeed = 'IncreaseSpeed',
  DecreaseSpeed = 'DecreaseSpeed',
  ToggleDirection = 'ToggleDirection',
  TogglePower = 'TogglePower',
  ToggleOpen = 'ToggleOpen',
  TurnLightOff = 'TurnLightOff',
  Open = 'Open',
  Close = 'Close',
  Preset = 'Preset'
}
